-- PROLOG KOPI FIELD AUDIT — Supabase schema
-- Run in Supabase SQL Editor. Keep RLS enabled and expose only the tables you intend the browser to use.

begin;

create extension if not exists pgcrypto;

create table if not exists public.outlets (
  name text primary key,
  status text not null default 'ACTIVE',
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.crews (
  id uuid primary key default gen_random_uuid(),
  crew_id text unique not null,
  outlet text not null references public.outlets(name),
  name text not null,
  position text not null default 'Staff',
  status text not null default 'Aktif',
  created_at timestamptz not null default now()
);

create table if not exists public.sops (
  code text primary key,
  title text not null,
  category text, pic text, executor text, frequency text,
  indicator_count integer default 0, source text
);

create table if not exists public.indicators (
  id bigint generated by default as identity primary key,
  sop_code text not null references public.sops(code) on delete cascade,
  title text, type text, indicator text not null, priority text not null default 'NORMAL',
  unique (sop_code, indicator)
);

create table if not exists public.audits (
  id uuid primary key default gen_random_uuid(),
  audit_date date not null, audit_time time, outlet text not null references public.outlets(name),
  crew text not null, position text, shift text, sop_code text not null references public.sops(code),
  indicator text not null, score numeric(2,1) not null check(score between 1 and 5),
  status text, diagnosis text, risk_level text, needs_coaching boolean default false,
  recommendation text, finding text, action text, pic_action text, due_date date, follow_up text,
  auditor text, root_cause text, root_cause_detail text, diagnosis_type text, recurring_issue boolean default false,
  early_warning text, priority text, scope text, review_status text, evidence_url text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.coaching_actions (
  id uuid primary key default gen_random_uuid(),
  action_date date not null, outlet text not null references public.outlets(name), crew text not null,
  sop_code text references public.sops(code), finding text not null, category text, priority text, action text,
  pic text, due_date date, status text not null default 'OPEN', evidence_url text, supervisor_review text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at() returns trigger
language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

drop trigger if exists trg_audits_updated_at on public.audits;
create trigger trg_audits_updated_at before update on public.audits for each row execute function public.set_updated_at();
drop trigger if exists trg_actions_updated_at on public.coaching_actions;
create trigger trg_actions_updated_at before update on public.coaching_actions for each row execute function public.set_updated_at();

-- RLS baseline. For a production deployment, replace the sample policies with role-based policies tied to your team structure.
alter table public.outlets enable row level security;
alter table public.crews enable row level security;
alter table public.sops enable row level security;
alter table public.indicators enable row level security;
alter table public.audits enable row level security;
alter table public.coaching_actions enable row level security;

drop policy if exists outlets_select on public.outlets;
create policy outlets_select on public.outlets for select to anon, authenticated using (true);
drop policy if exists crews_select on public.crews;
create policy crews_select on public.crews for select to anon, authenticated using (true);
drop policy if exists sops_select on public.sops;
create policy sops_select on public.sops for select to anon, authenticated using (true);
drop policy if exists indicators_select on public.indicators;
create policy indicators_select on public.indicators for select to anon, authenticated using (true);

drop policy if exists audits_read on public.audits;
create policy audits_read on public.audits for select to anon, authenticated using (true);
drop policy if exists audits_insert on public.audits;
create policy audits_insert on public.audits for insert to anon, authenticated with check (true);
drop policy if exists actions_read on public.coaching_actions;
create policy actions_read on public.coaching_actions for select to anon, authenticated using (true);
drop policy if exists actions_insert on public.coaching_actions;
create policy actions_insert on public.coaching_actions for insert to anon, authenticated with check (true);
drop policy if exists actions_update on public.coaching_actions;
create policy actions_update on public.coaching_actions for update to anon, authenticated using (true) with check (true);

-- Realtime publication for live updates.
alter publication supabase_realtime add table public.audits;
alter publication supabase_realtime add table public.coaching_actions;

-- Optional: public bucket for demo evidence. Tighten this for production.
insert into storage.buckets (id, name, public) values ('audit-evidence','audit-evidence',true) on conflict (id) do nothing;

drop policy if exists evidence_upload on storage.objects;
create policy evidence_upload on storage.objects for insert to anon, authenticated with check (bucket_id='audit-evidence');
drop policy if exists evidence_read on storage.objects;
create policy evidence_read on storage.objects for select to anon, authenticated using (bucket_id='audit-evidence');

commit;
